name: PyTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7']
    name: Testing acltest with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies and script
        run: pip install -r requirements.txt .

      - name: Install flake8
        run: pip install flake8
      - name: Link with flake8
        run: flake8

      - name: Install pytest
        run: pip install -r test-requirements.txt
      - name: Test with pytest
        run: pytest tests/
